# NumPy 基础

NumPy 是高性能科学计算和数据分析的基础包，部分功能如下:

* ndarray, 具有矢量算术运算和复杂广播能力的快速且节省空间的多维数组
* 用于对整组数据进行快速运算的标准数学函数(无需编写循环)
* 线性代数、随机数生成以及博里叶变换功能
* 用于集成 C、C++、Frotarn 等语言编写的代码的工具

对于大部分数据分析应用而言，主要功能集中在:

* 用于数据整理和清理、子集构造和过滤、转换等快速的矢量化数组运算
* 常用的数组算法， 如排序、唯一化、集合运算等
* 高效的描述统计和数据聚合/摘要运算
* 用于异构数据集的合并/连接运算的数据对齐和关系型数据运算
* 将条件逻辑表述为数组表达式(而不是带有 if-elif-else分支的循环)
* 数据的分组运算(聚合、转换、函数应用等)

## 创建 ndarray

简单的方式是是用 array 函数， 接收一切序列型的对象(包括其他数组)

In [1]:
import numpy as np

In [3]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [4]:
# 嵌套序列 (比如由一组等长列表组成的列表)
data2 = [
    [1, 2, 3, 4],
    [5, 6, 7, 8]
]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
arr2.ndim

2

In [6]:
arr2.shape

(2, 4)

### 使用 zeros ones 创建全是 0 或 1 的数组, empty 创建没有任何值得数组

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
np.ones((3, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [14]:
np.empty((2, 6))

array([[6.95331873e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [12]:
np.empty((2, 3, 2))

array([[[6.95331873e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

### arange 是 Python 内置函数 range 的数组版

In [15]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### 数组创建函数

| 函数 | 说明 |
| :--: | :--: |
| array| 将输入数据 (列表、数组、元组或其他序列类型) 转换为 ndarray, 要么推断出 dtype, 要么显示指定 dtype, 默认直接复制输入数据 |
| asarry | 将输入转换为 ndarrary, 如果输入本身就是一个 ndarrary 就不进行复制 |
| arange | 类似于内置的 range, 但返回的是一个 ndarrary 而不是列表 |
| ones, ones_like | 根据指定的shape 和 dtype 创建一个全 1 的数组， ones_like以另一个数组为参数， 并根据 shape 和 dtype 创建一个全 1 的数组 |
| zeros, zeros_like | 类似于 ones 和 ones_like, 只不过产生的是全 0 数组而已 |
| empty, empty_like | 创建新数组，只分配内存空间但不填充任何值 |
| eye, identity | 创建一个正方的 N * N 单位的矩阵 (对角线为 1， 其余为 0)


## NumPy 的数据类型

| 类型 | 类型代码 | 说明 |
| :--: | :------: | :--: |
| int8/16/32/64, uint8/16/32/64 | i1/2/4/8, u1/2/4/8 | 有符号和无符号的整型 |
| float16/32/64/128 | f2/f4/f8/f16 | 浮点数, C的float和float32兼容， C的double和float64兼容 |
|complex64/128/256 | c8/16/32 | 复数 |
| bool | ? | 布尔类型 |
| object | O | Python 对象类型 |
| string_ | S | 固定长度的字符串类型(每个字符1个字节)， 如创建长度10的字符串， S10 |
| unicode_ | U | 固定长度的unicode 类型，和字符串一样 |

python3 版本的 numpy 应该在字符串和unicode上面统一了。可以通过 ndarray 的 astype 方法显式的转换其 dtype

In [17]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [18]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [19]:
# 整数被截断
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [20]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [22]:
# 如果某字符串数组表示的全是数字，也可以用 astype 将其转换为数值形式
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [24]:
# astype 会创建一个新的数组，不管 dtype是否变化了
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

## 数组和标量之间的运算

大小相等数组之间任何算术运算都会将运算应用到元素级:

In [25]:
arr = np.array([
    [1., 2., 3.],
    [4., 5., 6.]
])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [26]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [27]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

## 基本的索引和切片

In [28]:
# 一维数组很简单，类似 Python 列表的功能
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr[5]

5

In [30]:
arr[5:8]

array([5, 6, 7])

In [32]:
# 当将一个标量赋值给一个切片时，该值会自动传播到整个选区。
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

数组的切片时原始数组的试图，不会被复制

In [33]:
arr_slice = arr[5:8]

In [36]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [38]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [41]:
# 如果需要显式的复制需要使用 copy() 方法
arr_copy = arr[5:8].copy()
arr_copy

array([64, 64, 64])

对于高维度数组，各索引位置上的元素不再是标量而是一维数组:

In [43]:
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
arr2d[2]

array([7, 8, 9])

可以使用 逗号隔开索引列表选取单个元素，也可以用两个索引符号

In [44]:
arr2d[0][2]

3

In [45]:
arr2d[0, 2]

3

在多维数组中，如果省略了后面的索引，则返回对象会是一个低纬度低一点的 ndarray

In [55]:
arr3d = np.arange(1,13).reshape(2, 2, 3)
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [57]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [61]:
# 标量值和数组都可以被赋值给 arr3d[0]
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [62]:
# 以此类推
arr3d[1, 0]

array([7, 8, 9])

切片索引， 可以在一个或多个轴上进行切片，也可以跟整数索引混合使用

In [63]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
arr2d[: 2]

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
arr2d[: 2, 1:]

array([[2, 3],
       [5, 6]])

In [66]:
arr2d[1, : 2]

array([4, 5])

In [67]:
arr2d[2, : 1]

array([7])

In [68]:
arr2d[:, : 1]

array([[1],
       [4],
       [7]])

### 布尔型索引

In [69]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [70]:
data

array([[ 1.19440205, -1.31446155, -0.75343479,  0.40128211],
       [ 0.88485913, -1.96446538, -0.31507245, -0.57414591],
       [-0.09993978, -0.85747275, -2.26391577,  0.89792476],
       [-0.27018885,  1.87316402, -1.01503967,  1.13262095],
       [-0.51496857, -0.9078152 ,  0.1360847 , -1.13745226],
       [ 0.13727   ,  0.28318574, -0.06786803, -0.82388882],
       [ 0.27387145, -1.20641031,  0.58841879,  1.5942146 ]])

假设每个名字都对应 data 数组中的一行，而我们想要选出对应于名字 'Bob' 的所有行。跟算术运算一样，数组的比较运算也是矢量化的

In [71]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

这个布尔型数组可以用于数组的索引

In [72]:
data[names == 'Bob']

array([[ 1.19440205, -1.31446155, -0.75343479,  0.40128211],
       [-0.27018885,  1.87316402, -1.01503967,  1.13262095]])

布尔型数组的长度必须跟被索引的轴长度一致，此外，还可以将布尔型数组跟切片、整数混合使用

In [73]:
data[names == 'Bob', 2:]

array([[-0.75343479,  0.40128211],
       [-1.01503967,  1.13262095]])

In [75]:
data[names == 'Bob', 3]

array([0.40128211, 1.13262095])

In [78]:
data[names != 'Bob']

array([[ 0.88485913, -1.96446538, -0.31507245, -0.57414591],
       [-0.09993978, -0.85747275, -2.26391577,  0.89792476],
       [-0.51496857, -0.9078152 ,  0.1360847 , -1.13745226],
       [ 0.13727   ,  0.28318574, -0.06786803, -0.82388882],
       [ 0.27387145, -1.20641031,  0.58841879,  1.5942146 ]])

选取这个三个名字中的两个组合需要应用多个布尔条件，使用 & | 操作

In [81]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [82]:
data[mask]

array([[ 1.19440205, -1.31446155, -0.75343479,  0.40128211],
       [-0.09993978, -0.85747275, -2.26391577,  0.89792476],
       [-0.27018885,  1.87316402, -1.01503967,  1.13262095],
       [-0.51496857, -0.9078152 ,  0.1360847 , -1.13745226]])

Tip: 通过布尔型索引选取数组中的数据，将总是创建数据的副本，即使返回一模一样的数组也是如此

In [83]:
data[data < 0] = 0

In [84]:
data

array([[1.19440205, 0.        , 0.        , 0.40128211],
       [0.88485913, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.89792476],
       [0.        , 1.87316402, 0.        , 1.13262095],
       [0.        , 0.        , 0.1360847 , 0.        ],
       [0.13727   , 0.28318574, 0.        , 0.        ],
       [0.27387145, 0.        , 0.58841879, 1.5942146 ]])

In [85]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.88485913, 0.        , 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.13727   , 0.28318574, 0.        , 0.        ],
       [0.27387145, 0.        , 0.58841879, 1.5942146 ]])

### 花式索引

指的是利用整数数组进行索引

In [86]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

为了以特定顺序选取行子集， 只需传入一个用于指定顺序的整数列或 ndarray 即可:

In [87]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [88]:
# 使用复数，将从行尾开始
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

一次传入多个索引数组会有一点特别，它返回的是一个一维数组，其中的元素对应各个索引元组:

In [89]:
arr = np.arange(32).reshape( (8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [90]:
arr[ [1, 5, 7, 2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [91]:
arr[ [1, 5, 7, 2], [0, 3, 1, 2] ]

array([ 4, 23, 29, 10])

## 数组转置和轴对换

转置是重塑的一种特殊形式，它返回的是源数据的试图

In [94]:
arr = np.arange(15).reshape( (3, 5) )
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [95]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

对于高维数组， transpose需要得到一个由轴编号组成的元组才能对这些轴进转置:

In [96]:
arr = np.arange(16).reshape( (2, 2, 4) )
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [97]:
arr.transpose( (1, 0, 2) )

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

## 通用函数: 快速的元素级数组函数

通用函数是一种对 ndarray 中的数据执行元素级运算的函数。可看作简单函数的矢量化包装器

In [98]:
arr = np.arange(10)
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [99]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

以上都是一元通用函数，也有二元通用函数

In [100]:
x = np.random.randn(8)
y = np.random.randn(8)
x

array([-0.52582003,  0.53610926, -0.69022698,  1.12120307,  0.26907485,
        0.45896601,  0.79629657,  0.27026127])

In [101]:
y

array([ 0.49377251, -1.19328643,  1.0640162 ,  0.66838265, -0.02910239,
       -0.29774447, -1.30120523,  0.84582718])

In [102]:
# 元素级最大值
np.maximum(x, y)

array([0.49377251, 0.53610926, 1.0640162 , 1.12120307, 0.26907485,
       0.45896601, 0.79629657, 0.84582718])

一元通用函数

| 函数 | 说明 |
| :--: | :--: |
| abs, fabs | 计算整数、浮点数或复数的绝对值，对于非复数值，可以用更快的fabs |
| sqrt | 计算各元素的平方根，相等于 arr ** 0.5 |
| square | 计算各元素的平方， 相当于 arr ** 2 |
| exp | 计算各元素的指数 e<sup>x</sup> |
| log, log10, log2, log1p | 分别对自然对数， 底数为10的log, 底数为2的log,log(1 + x) |
| sign | 计算各元素的正负号: 1 (正数), 0 (零), -1 (负数) |
| ceil | 计算各元素的ceiling值， 即大于或等于该值得最小整数 |
| floor | 计算各元素的floor值， 即小于等于该值的最大整数 |
| rint | 将各元素值四舍五入到最接近的整数，保留 dtype |
| modf | 将数组的小数和整数部分以两个独立数组的形式返回 |
| isnan | 返回一个表示 "哪些值是NaN" 的布尔型数组 |
| isfinite, isinf | 分别返回一个表示 "哪些元素是有穷的" 或 "哪些元素是无穷的" 布尔型数组 |
| cos, cosh, sin, sinh, tan, tanh | 普通型和双曲型三角函数 |
| arccos,arccosh, arcsin, arcsinh, arctan, arctanh | 反三角函数 |
| logical_not | 计算各元素 not x 的真值， 相当于 -arr |

二元通用函数

| 函数 | 说明 |
| :--: | :--: |
| add | 将数组中对应的元素相加 |
| subtract | 从第一个数组中减去第二个数组中的元素 |
| multiply | 数组元素相乘 |
| divide,floor_divide | 除法或向下圆整除法(丢弃余数) |
| power | 对第一个数组中的元素A, 根据第二个数组中的相应元素B，计算 A<sup>B</sup> |
| maximum, fmax | 元素级的最大值计算， fmax 将忽略 NaN |
| minimum, fmin | 元素级的最小值计算，fmin 将忽略 NaN |
| mod | 元素级的求模计算 |
| copysign | 将第二个数组中的值得符合复制给第一个数组中的值 |
| greater, greater_equal, less, less_equal, equal, not_equal | 执行元素级的比较运算，最终产生布尔型数组，相当于中缀运算符 > >= < <= == != |
| logical_and, logical_or, logical_xor | 执行元素级的真值逻辑运算，相当于 与或非 |

## 利用数组进行数据处理

NumPy数组可以将许多数据处理任务表述为简洁的数组表达式，用数组表达式代替循环的做法，通常被称为矢量化，一般来说矢量化数组运算要比等价的纯Python 方式快上一两个数量级。