# NumPy 基础

NumPy 是高性能科学计算和数据分析的基础包，部分功能如下:

* ndarray, 具有矢量算术运算和复杂广播能力的快速且节省空间的多维数组
* 用于对整组数据进行快速运算的标准数学函数(无需编写循环)
* 线性代数、随机数生成以及博里叶变换功能
* 用于集成 C、C++、Frotarn 等语言编写的代码的工具

对于大部分数据分析应用而言，主要功能集中在:

* 用于数据整理和清理、子集构造和过滤、转换等快速的矢量化数组运算
* 常用的数组算法， 如排序、唯一化、集合运算等
* 高效的描述统计和数据聚合/摘要运算
* 用于异构数据集的合并/连接运算的数据对齐和关系型数据运算
* 将条件逻辑表述为数组表达式(而不是带有 if-elif-else分支的循环)
* 数据的分组运算(聚合、转换、函数应用等)

## 创建 ndarray

简单的方式是是用 array 函数， 接收一切序列型的对象(包括其他数组)

In [1]:
import numpy as np

In [2]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [3]:
# 嵌套序列 (比如由一组等长列表组成的列表)
data2 = [
    [1, 2, 3, 4],
    [5, 6, 7, 8]
]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
arr2.ndim

2

In [5]:
arr2.shape

(2, 4)

### 使用 zeros ones 创建全是 0 或 1 的数组, empty 创建没有任何值得数组

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [8]:
np.ones((3, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [9]:
np.empty((2, 6))

array([[6.95329928e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [10]:
np.empty((2, 3, 2))

array([[[6.95329928e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

### arange 是 Python 内置函数 range 的数组版

In [11]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### 数组创建函数

| 函数 | 说明 |
| :--: | :--: |
| array| 将输入数据 (列表、数组、元组或其他序列类型) 转换为 ndarray, 要么推断出 dtype, 要么显示指定 dtype, 默认直接复制输入数据 |
| asarry | 将输入转换为 ndarrary, 如果输入本身就是一个 ndarrary 就不进行复制 |
| arange | 类似于内置的 range, 但返回的是一个 ndarrary 而不是列表 |
| ones, ones_like | 根据指定的shape 和 dtype 创建一个全 1 的数组， ones_like以另一个数组为参数， 并根据 shape 和 dtype 创建一个全 1 的数组 |
| zeros, zeros_like | 类似于 ones 和 ones_like, 只不过产生的是全 0 数组而已 |
| empty, empty_like | 创建新数组，只分配内存空间但不填充任何值 |
| eye, identity | 创建一个正方的 N * N 单位的矩阵 (对角线为 1， 其余为 0)


## NumPy 的数据类型

| 类型 | 类型代码 | 说明 |
| :--: | :------: | :--: |
| int8/16/32/64, uint8/16/32/64 | i1/2/4/8, u1/2/4/8 | 有符号和无符号的整型 |
| float16/32/64/128 | f2/f4/f8/f16 | 浮点数, C的float和float32兼容， C的double和float64兼容 |
|complex64/128/256 | c8/16/32 | 复数 |
| bool | ? | 布尔类型 |
| object | O | Python 对象类型 |
| string_ | S | 固定长度的字符串类型(每个字符1个字节)， 如创建长度10的字符串， S10 |
| unicode_ | U | 固定长度的unicode 类型，和字符串一样 |

python3 版本的 numpy 应该在字符串和unicode上面统一了。可以通过 ndarray 的 astype 方法显式的转换其 dtype

In [12]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [13]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [14]:
# 整数被截断
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [15]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [16]:
# 如果某字符串数组表示的全是数字，也可以用 astype 将其转换为数值形式
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [17]:
# astype 会创建一个新的数组，不管 dtype是否变化了
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

## 数组和标量之间的运算

大小相等数组之间任何算术运算都会将运算应用到元素级:

In [18]:
arr = np.array([
    [1., 2., 3.],
    [4., 5., 6.]
])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [19]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [20]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

## 基本的索引和切片

In [21]:
# 一维数组很简单，类似 Python 列表的功能
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr[5]

5

In [23]:
arr[5:8]

array([5, 6, 7])

In [24]:
# 当将一个标量赋值给一个切片时，该值会自动传播到整个选区。
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

数组的切片时原始数组的试图，不会被复制

In [25]:
arr_slice = arr[5:8]

In [26]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [27]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [28]:
# 如果需要显式的复制需要使用 copy() 方法
arr_copy = arr[5:8].copy()
arr_copy

array([64, 64, 64])

对于高维度数组，各索引位置上的元素不再是标量而是一维数组:

In [29]:
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
arr2d[2]

array([7, 8, 9])

可以使用 逗号隔开索引列表选取单个元素，也可以用两个索引符号

In [30]:
arr2d[0][2]

3

In [31]:
arr2d[0, 2]

3

在多维数组中，如果省略了后面的索引，则返回对象会是一个低纬度低一点的 ndarray

In [32]:
arr3d = np.arange(1,13).reshape(2, 2, 3)
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [33]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [35]:
# 标量值和数组都可以被赋值给 arr3d[0]
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [36]:
# 以此类推
arr3d[1, 0]

array([7, 8, 9])

切片索引， 可以在一个或多个轴上进行切片，也可以跟整数索引混合使用

In [37]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr2d[: 2]

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
arr2d[: 2, 1:]

array([[2, 3],
       [5, 6]])

In [40]:
arr2d[1, : 2]

array([4, 5])

In [41]:
arr2d[2, : 1]

array([7])

In [42]:
arr2d[:, : 1]

array([[1],
       [4],
       [7]])

### 布尔型索引

In [43]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [44]:
data

array([[ 0.04746823, -1.10828719,  0.75597796,  0.75728712],
       [ 0.90948108,  0.70682017, -1.25841386,  0.51899692],
       [-1.01528259,  2.62054949,  0.59228677,  0.57204784],
       [ 1.52861527, -1.09941515, -1.36413522, -0.27122275],
       [-1.52465793,  0.15671397,  0.97939569,  0.26682989],
       [ 1.28448629,  0.67626029, -0.19708585,  1.01609895],
       [-1.25456154, -1.9712079 , -0.31145019, -1.30758244]])

假设每个名字都对应 data 数组中的一行，而我们想要选出对应于名字 'Bob' 的所有行。跟算术运算一样，数组的比较运算也是矢量化的

In [45]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

这个布尔型数组可以用于数组的索引

In [46]:
data[names == 'Bob']

array([[ 0.04746823, -1.10828719,  0.75597796,  0.75728712],
       [ 1.52861527, -1.09941515, -1.36413522, -0.27122275]])

布尔型数组的长度必须跟被索引的轴长度一致，此外，还可以将布尔型数组跟切片、整数混合使用

In [47]:
data[names == 'Bob', 2:]

array([[ 0.75597796,  0.75728712],
       [-1.36413522, -0.27122275]])

In [48]:
data[names == 'Bob', 3]

array([ 0.75728712, -0.27122275])

In [49]:
data[names != 'Bob']

array([[ 0.90948108,  0.70682017, -1.25841386,  0.51899692],
       [-1.01528259,  2.62054949,  0.59228677,  0.57204784],
       [-1.52465793,  0.15671397,  0.97939569,  0.26682989],
       [ 1.28448629,  0.67626029, -0.19708585,  1.01609895],
       [-1.25456154, -1.9712079 , -0.31145019, -1.30758244]])

选取这个三个名字中的两个组合需要应用多个布尔条件，使用 & | 操作

In [50]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [51]:
data[mask]

array([[ 0.04746823, -1.10828719,  0.75597796,  0.75728712],
       [-1.01528259,  2.62054949,  0.59228677,  0.57204784],
       [ 1.52861527, -1.09941515, -1.36413522, -0.27122275],
       [-1.52465793,  0.15671397,  0.97939569,  0.26682989]])

Tip: 通过布尔型索引选取数组中的数据，将总是创建数据的副本，即使返回一模一样的数组也是如此

In [52]:
data[data < 0] = 0

In [53]:
data

array([[0.04746823, 0.        , 0.75597796, 0.75728712],
       [0.90948108, 0.70682017, 0.        , 0.51899692],
       [0.        , 2.62054949, 0.59228677, 0.57204784],
       [1.52861527, 0.        , 0.        , 0.        ],
       [0.        , 0.15671397, 0.97939569, 0.26682989],
       [1.28448629, 0.67626029, 0.        , 1.01609895],
       [0.        , 0.        , 0.        , 0.        ]])

In [54]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.90948108, 0.70682017, 0.        , 0.51899692],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [1.28448629, 0.67626029, 0.        , 1.01609895],
       [0.        , 0.        , 0.        , 0.        ]])

### 花式索引

指的是利用整数数组进行索引

In [55]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

为了以特定顺序选取行子集， 只需传入一个用于指定顺序的整数列或 ndarray 即可:

In [56]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [57]:
# 使用复数，将从行尾开始
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

一次传入多个索引数组会有一点特别，它返回的是一个一维数组，其中的元素对应各个索引元组:

In [58]:
arr = np.arange(32).reshape( (8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [59]:
arr[ [1, 5, 7, 2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [60]:
arr[ [1, 5, 7, 2], [0, 3, 1, 2] ]

array([ 4, 23, 29, 10])

## 数组转置和轴对换

转置是重塑的一种特殊形式，它返回的是源数据的试图

In [61]:
arr = np.arange(15).reshape( (3, 5) )
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [62]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

对于高维数组， transpose需要得到一个由轴编号组成的元组才能对这些轴进转置:

In [63]:
arr = np.arange(16).reshape( (2, 2, 4) )
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [64]:
arr.transpose( (1, 0, 2) )

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

## 通用函数: 快速的元素级数组函数

通用函数是一种对 ndarray 中的数据执行元素级运算的函数。可看作简单函数的矢量化包装器

In [65]:
arr = np.arange(10)
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [66]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

以上都是一元通用函数，也有二元通用函数

In [67]:
x = np.random.randn(8)
y = np.random.randn(8)
x

array([-0.08367901,  0.21488411, -2.55693382, -0.70616756,  0.95191634,
        1.32935266,  0.49222621, -0.76158936])

In [68]:
y

array([ 0.58426859, -2.77892607,  0.06277106,  1.02120781,  0.11304644,
        0.72204869,  0.72360855,  1.00250641])

In [69]:
# 元素级最大值
np.maximum(x, y)

array([0.58426859, 0.21488411, 0.06277106, 1.02120781, 0.95191634,
       1.32935266, 0.72360855, 1.00250641])

一元通用函数

| 函数 | 说明 |
| :--: | :--: |
| abs, fabs | 计算整数、浮点数或复数的绝对值，对于非复数值，可以用更快的fabs |
| sqrt | 计算各元素的平方根，相等于 arr ** 0.5 |
| square | 计算各元素的平方， 相当于 arr ** 2 |
| exp | 计算各元素的指数 e<sup>x</sup> |
| log, log10, log2, log1p | 分别对自然对数， 底数为10的log, 底数为2的log,log(1 + x) |
| sign | 计算各元素的正负号: 1 (正数), 0 (零), -1 (负数) |
| ceil | 计算各元素的ceiling值， 即大于或等于该值得最小整数 |
| floor | 计算各元素的floor值， 即小于等于该值的最大整数 |
| rint | 将各元素值四舍五入到最接近的整数，保留 dtype |
| modf | 将数组的小数和整数部分以两个独立数组的形式返回 |
| isnan | 返回一个表示 "哪些值是NaN" 的布尔型数组 |
| isfinite, isinf | 分别返回一个表示 "哪些元素是有穷的" 或 "哪些元素是无穷的" 布尔型数组 |
| cos, cosh, sin, sinh, tan, tanh | 普通型和双曲型三角函数 |
| arccos,arccosh, arcsin, arcsinh, arctan, arctanh | 反三角函数 |
| logical_not | 计算各元素 not x 的真值， 相当于 -arr |

二元通用函数

| 函数 | 说明 |
| :--: | :--: |
| add | 将数组中对应的元素相加 |
| subtract | 从第一个数组中减去第二个数组中的元素 |
| multiply | 数组元素相乘 |
| divide,floor_divide | 除法或向下圆整除法(丢弃余数) |
| power | 对第一个数组中的元素A, 根据第二个数组中的相应元素B，计算 A<sup>B</sup> |
| maximum, fmax | 元素级的最大值计算， fmax 将忽略 NaN |
| minimum, fmin | 元素级的最小值计算，fmin 将忽略 NaN |
| mod | 元素级的求模计算 |
| copysign | 将第二个数组中的值得符合复制给第一个数组中的值 |
| greater, greater_equal, less, less_equal, equal, not_equal | 执行元素级的比较运算，最终产生布尔型数组，相当于中缀运算符 > >= < <= == != |
| logical_and, logical_or, logical_xor | 执行元素级的真值逻辑运算，相当于 与或非 |

## 利用数组进行数据处理

NumPy数组可以将许多数据处理任务表述为简洁的数组表达式，用数组表达式代替循环的做法，通常被称为矢量化，一般来说矢量化数组运算要比等价的纯Python 方式快上一两个数量级。

### 将条件逻辑表述为数组运算

numpy.where 函数是三元表达式 x if condition else y 的矢量化版本

In [70]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

假设需要根据 cond 中的值选取 xarr 和 yarr 的值: 当 cond 中的值为 True 时， 选取 xarr 的值，否则从 yarr 中选取。 列表推导式如下:

In [71]:
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

这有几个问题， 第一，它对大数组的处理速度不是很快，第二， 无法用于多维数组。若用 np.where, 则可以非常简洁高效:

In [72]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

np.where 的第二个和第三个参数不必是数组，可以是标量。在数据分析工作中，where 通常用于根据另一个数组产生一个新的数组。假设有一个随机数据组成的矩阵，希望将所有正值替换为 2， 将所有负值替换为 -2 , 若用 np.where, 则非常简单:

In [75]:
arr = np.random.randn(4, 4)
arr

array([[ 0.31503266, -0.9220972 ,  2.20965765, -1.569991  ],
       [ 1.20429853, -0.61421313,  0.26426784, -0.12394017],
       [-1.51883098,  0.83351013,  0.45839753, -1.09772008],
       [-1.1998245 ,  2.80245515,  0.77005878,  0.96200374]])

In [76]:
np.where(arr > 0, 2, -2)

array([[ 2, -2,  2, -2],
       [ 2, -2,  2, -2],
       [-2,  2,  2, -2],
       [-2,  2,  2,  2]])

In [77]:
# 只将正值设置为 2
np.where(arr > 0, 2, arr)

array([[ 2.        , -0.9220972 ,  2.        , -1.569991  ],
       [ 2.        , -0.61421313,  2.        , -0.12394017],
       [-1.51883098,  2.        ,  2.        , -1.09772008],
       [-1.1998245 ,  2.        ,  2.        ,  2.        ]])

传递给 where 的数组大小可以不相等，甚至可以是标量值。

### 数学和统计方法

可以通过数组上的一组数学函数对整个数组或某个轴向的数据进行统计计算。sum, mean 以及标准差 std 等聚合计算既可以当作数组的实例方法调用，也可以当作顶级 NumPy 函数使用：

In [83]:
arr = np.random.randn(5, 4) # 正态分布的数据
arr

array([[ 0.77085785,  0.60842589,  0.69349163,  0.26812301],
       [ 1.47259654, -1.13051014,  0.9929083 ,  0.08860534],
       [-0.24203782,  0.31051675, -0.04242556,  0.06160788],
       [ 0.01820186,  0.75832529, -0.4091595 ,  0.63197109],
       [-1.11217994,  0.12937892,  0.71039693, -2.80888523]])

In [79]:
arr.mean()

0.0828034111047696

In [80]:
np.mean(arr)

0.0828034111047696

In [81]:
arr.sum()

1.6560682220953922

mean 和 sum 这类的函数可以接受一个 axis 参数(用于计算该轴向上的统计值)，最终结果是一个少一维的数组:

In [84]:
arr.mean(axis=1)

array([ 0.58522459,  0.35590001,  0.02191531,  0.24983469, -0.77032233])

In [85]:
arr.sum(0)

array([ 0.90743849,  0.67613671,  1.94521179, -1.75857791])

基本数组统计方法

| 方法 | 说明 |
| :--: | :--: |
| sum | 对数组中全部或某轴向的元素求和。零长度的数组的 sum 为 0 |
| mean | 算术平均数，零长度的数组的 mean 为 NaN |
| std, var | 分别为标准差和方差，自由度可调 (默认为 n) |
| min, max | 最大值和最小值 |
| argmin, argmax | 分别为最大和最小元素的索引 |
| cumsum | 所有元素的累计和 |
| cumprod | 所有元素的累计积 |

### 用于布尔型数组的方法

在上面这些方法中，布尔值会被强制转换为 1 (True) 和 0 (False), 因此，sum 经常被用来对布尔型数组中的 True 值计数:

In [92]:
arr = np.random.randn(100)
(arr > 0).sum()

52

另外还有两个方法 any 和 all ， 他们对布尔型数组非常有用, any 用于测试数组中是否存在一个或多个 True, 而 all 则检查数组中所有值是否都是 True, 这两个方法也可以用于非布尔型数组，所有非 0 元素将会被当作 True .

In [93]:
bools = np.array([False, False, True, False])
bools.any()

True

In [94]:
bools.all()

False

### 排序

和 Python 内置的列表类型一样， NumPy 数组也可以通过 sort 方法就地排序:

In [95]:
arr = np.random.randn(8)
arr

array([ 0.16127274, -0.79197472, -2.28741308, -0.20286701, -0.0349847 ,
       -0.97745823, -0.38588827, -0.18356067])

In [96]:
arr.sort()
arr

array([-2.28741308, -0.97745823, -0.79197472, -0.38588827, -0.20286701,
       -0.18356067, -0.0349847 ,  0.16127274])

多维数组可以在任何一个轴向上进行排序，只需要将轴编号传给 sort 即可: 

In [97]:
arr = np.random.randn(5, 3)
arr

array([[-0.31839956, -1.12421184, -0.85662216],
       [-0.03242331, -0.56125059,  0.71956182],
       [ 0.59446252, -1.56208409,  0.49650415],
       [-0.55230819, -2.1339157 ,  2.3160945 ],
       [-0.77115725, -1.32555862,  0.85441039]])

In [98]:
arr.sort(1)
arr

array([[-1.12421184, -0.85662216, -0.31839956],
       [-0.56125059, -0.03242331,  0.71956182],
       [-1.56208409,  0.49650415,  0.59446252],
       [-2.1339157 , -0.55230819,  2.3160945 ],
       [-1.32555862, -0.77115725,  0.85441039]])

顶级方法 np.sort 返回的是数组的已排序副本， 而就地排序则会修改数组本身。计算数组分位数最简单的办法就是对其进行排序，然后选取特定位置的值:

In [99]:
large_arr = np.random.randn(1000)
large_arr.sort()

In [100]:
# 5% 分位数
large_arr[int(0.05 * len(large_arr))]

-1.6116838173383143

### 唯一化以及其他的集合逻辑

NumPy 提供了一些针对一维 ndarray 的基本集合运算。最常用的可能就是 np.unique, 它用于找出数组中的唯一值并返回已排序的结果:

In [101]:
names = np.array( ['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'] )
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [102]:
ints = np.array( [3, 3, 3, 2, 2, 1, 1, 4, 4] )
np.unique(ints)

array([1, 2, 3, 4])

np.unique 等价的纯 Python 代码

In [103]:
sorted(set(names))

['Bob', 'Joe', 'Will']

另一个函数 np.in1d 用于测试一个数组中的值在另一个数组中的成员资格，返回一个布尔型数组:

In [105]:
values = np.array( [6, 0, 0, 3, 2, 5, 6] )

In [107]:
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

数组的集合运算

| 方法 | 说明 |
| :--: | :--: |
| unique(x) | 计算 x 中的唯一元素，并返回有序结果 |
| intersect1d(x, y) | 计算 x 和 y 中的公共元素，并返回有序结果 |
| union1d(x, y) | 计算 x 和 y 的并集, 并返回有序结果 |
| in1d(x, y) | 得到一个表示 "x 的元素是否包含于 y" 的布尔型数组 |
| setdiff1d(x, y) | 集合的差， 即元素在 x 中且不在 y 中 |
| setxor1d(x, y) | 集合的对称差, 即存在一个数组中但不同时存在于两个数组中的元素 |

## 用于数组的文件输入输出

### 将数组以二进制格式保存到磁盘

np.save 和 np.load 是读写磁盘数组数据的两个主要函数。默认情况下，数组式以未压缩的原始二进制格式保存在扩展名为 .npy 的文件中。

In [108]:
arr = np.arange(10)
np.save('some_array', arr)

如果文件路径末尾没有扩展名 .npy, 则该扩展名会被自动加上，然后可以通过 np.load 读取磁盘桑的数组:

In [109]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

通过 np.savez 可以将多个数组保存到一个压缩文件中，将数组以关键字参数的形式传入即可:

In [110]:
np.savez('array_archive.npz', a=arr, b=arr)

加载 .npz 文件时，你会得到一个类似字典的对象，该对象会对各个数组进行延迟加载:

In [111]:
arch = np.load('array_archive.npz')

In [112]:
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 存取文本文件

从文件中加载文本是一个非常标准的任务, 主要有 np.loadtxt 和 np.genfromtxt 

## 线性代数

NumPy 提供了一个用于矩阵乘法的 dot 函数

In [113]:
x = np.array([
    [1., 2., 3.],
    [4., 5., 6.]
])
y = np.array([
    [6., 23.],
    [-1, 7],
    [8, 9]
])

In [114]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [115]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [116]:
x.dot(y) # 相当于 np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [118]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

一个二维数组跟一个大小合适的一维数组的矩阵点积运算之后将会得到一个一维数组:

In [119]:
np.dot(x, np.ones(3))

array([ 6., 15.])

numpy.linalg 中有一组标准的矩阵分解运算以及诸如求逆和行列式之类的东西

In [120]:
from numpy.linalg import inv, qr

In [124]:
X = np.random.randn(5, 5)
X

array([[ 0.27126899, -0.22084943, -0.33256169, -0.39796982,  0.56171627],
       [ 0.1614516 ,  2.07876749,  1.94815012,  0.04674741, -0.29659498],
       [ 0.8454607 , -0.72504634,  0.30845179,  0.21523288, -0.29970528],
       [-0.57459631, -0.47669258,  1.47652209, -2.22998806, -0.46389791],
       [ 0.01120233, -0.17178317, -1.2001086 , -0.78868506, -0.6633816 ]])

In [125]:
mat = X.T.dot(X)

In [126]:
inv(mat)

array([[ 1.41258378,  0.24856264, -0.14318448, -0.51400545,  0.37415687],
       [ 0.24856264,  0.4194178 , -0.2288889 , -0.26909558,  0.19044019],
       [-0.14318448, -0.2288889 ,  0.27224503,  0.19023115, -0.05495372],
       [-0.51400545, -0.26909558,  0.19023115,  0.50934411, -0.42810495],
       [ 0.37415687,  0.19044019, -0.05495372, -0.42810495,  1.2982953 ]])

In [127]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -6.24500451e-17, -7.45931095e-17,
         3.33066907e-16, -1.11022302e-16],
       [-4.16333634e-17,  1.00000000e+00,  1.07552856e-16,
         1.52655666e-16, -3.05311332e-16],
       [ 1.11022302e-16,  2.49800181e-16,  1.00000000e+00,
        -1.66533454e-16, -1.11022302e-16],
       [ 4.99600361e-16,  0.00000000e+00, -9.71445147e-17,
         1.00000000e+00,  0.00000000e+00],
       [-5.55111512e-17, -8.32667268e-17,  2.77555756e-17,
         2.22044605e-16,  1.00000000e+00]])

In [128]:
q, r = qr(mat)

In [129]:
r

array([[-1.8172214 ,  0.02833462,  3.51711402, -5.63443033, -1.23621682],
       [ 0.        , -6.29813411, -6.50927086, -0.99808854,  0.34201269],
       [ 0.        ,  0.        , -4.45472046,  2.59343711,  0.72536714],
       [ 0.        ,  0.        ,  0.        , -1.82679918, -0.91680316],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.69874987]])

常用的 numpy.linalg 函数

| 函数 | 说明 |
| :--: | :--: |
| diag | 以一维数组的形式返回方阵的对角线(或非对角线)元素，或将一维数组转换为方阵(非对角线元素为 0) |
| dot | 矩阵乘法 |
| trace | 计算对角线元素的和 |
| det | 计算矩阵行列式 |
| eig | 计算方阵的本征值和本征向量 |
| inv | 计算矩阵的逆 |
| pinv | 计算矩阵的 Moore-Penrose 伪逆 |
| qr | 计算 QR 分解 |
| svd | 计算奇异值分解(SVD) |
| solve | 解线性方程组 Ax = b, 其中 A 为一个方阵 |
|lstsq | 计算 Ax = b 的最小二乘解 |

## 随机数生成

numpy.random 模块对 Python 内置的 random 进行了补充，增加了一些用于高效生产多种概率分布的样本值得函数。

In [131]:
samples = np.random.normal(size=(4, 4))
samples

array([[ 0.74440638,  0.4922941 ,  1.73008622,  0.9709314 ],
       [-0.1388101 ,  0.13564155,  1.18550717, -0.33306992],
       [ 1.20541347, -0.09235661, -1.34738375, -1.074321  ],
       [-0.21258513,  1.23800491,  0.7656023 , -1.09426124]])

部分 numpy.random 函数

| 函数 | 说明 |
| :--: | :--: |
| seed | 确定随机数生成器的种子 |
| permutation | 返回一个序列的随机排列或返回一个随机排列的范围 |
| shuffle | 对一个序列就地随机排列 |
| rand | 产生均匀分布的样本值 |
| randint | 从给定的上下限范围内随机选取整数 |
| randn | 产生正态分布(平均值为 0, 标准差为 1) 的样本值， 类似于 MATLAB 接口 |
| binomial | 产生二项分布的样本值 |
| normal | 产生正态(高斯)分布的样本值 |
| beta | 产生 Beta 分布的样本值 |
| chisquare | 产生卡方分布的样本值 |
| gamma | 产生 Gamma 分布的样本值 |
| uniform | 产生在 [0, 1) 中分布均匀的样本值 |